# Generated by Django 4.0.3 on 2024-03-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
