# Generated by Django 4.0.3 on 2024-03-15 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_snippet_embeddings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='project',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='document',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='projects.document'),
            preserve_default=False,
        ),
    ]
