# Generated by Django 4.0.3 on 2024-03-16 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_snippet_project_document_snippet_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
