# Generated by Django 5.0.3 on 2024-03-24 05:26

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_delete_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=projects.models.documents_directory_path),
        ),
    ]
